  CREATE TABLE IF NOT EXISTS AM_INVALID_TOKENS (
     UUID VARCHAR(255) NOT NULL,
     SIGNATURE VARCHAR(2048) NOT NULL,
     CONSUMER_KEY VARCHAR(255) NOT NULL,
     TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     EXPIRY_TIMESTAMP BIGINT NOT NULL,
     PRIMARY KEY (UUID)
  );

  CREATE TABLE IF NOT EXISTS IDN_INTERNAL_TOKEN_REVOCATION_CONSUMER_KEY_EVENTS (
      ID INTEGER NOT NULL AUTO_INCREMENT,
      CONSUMER_KEY VARCHAR(255) NOT NULL,
      IS_REVOKE_APP_ONLY BOOLEAN NOT NULL DEFAULT FALSE,
      TIME_REVOKED VARCHAR(255) NOT NULL,
      TENANT_ID INTEGER NOT NULL,
      PRIMARY KEY (ID),
      UNIQUE (CONSUMER_KEY, IS_REVOKE_APP_ONLY)
  );

  CREATE TABLE IF NOT EXISTS IDN_INTERNAL_TOKEN_REVOCATION_USER_EVENTS (
      ID INTEGER NOT NULL AUTO_INCREMENT,
      USER_ID VARCHAR(255) NOT NULL,
      TIME_REVOKED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (ID),
      UNIQUE (USER_ID)
  );