  CREATE TABLE IF NOT EXISTS AM_INVALID_TOKENS (
     UUID VARCHAR(255) NOT NULL,
     SIGNATURE VARCHAR(2048) NOT NULL,
     CONSUMER_KEY VARCHAR(255) NOT NULL,
     TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     EXPIRY_TIMESTAMP BIGINT NOT NULL,
     PRIMARY KEY (UUID)
  );

  CREATE TABLE IF NOT EXISTS IDN_INTERNAL_TOKEN_REVOCATION_CONSUMER_KEY_EVENTS (
     CONSUMER_KEY VARCHAR(255) NOT NULL,
     TIME_REVOKED TIMESTAMP NOT NULL,
     ORGANIZATION VARCHAR(100),
     PRIMARY KEY (CONSUMER_KEY, ORGANIZATION)
  );

  CREATE TABLE IF NOT EXISTS IDN_INTERNAL_TOKEN_REVOCATION_USER_EVENTS (
     SUBJECT_ID VARCHAR(255) NOT NULL,
     SUBJECT_ID_TYPE VARCHAR(100) NOT NULL,
     TIME_REVOKED TIMESTAMP NOT NULL,
     ORGANIZATION VARCHAR(100),
     PRIMARY KEY (SUBJECT_ID, SUBJECT_ID_TYPE, ORGANIZATION)
  );